name: digividya
description: "DigiVidya - Smart Education Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.0.0

  # State Management
  provider: ^6.1.5+1

  # Utilities
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  pinput: ^5.0.0
  intl: ^0.20.2

  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0
  pdf: ^3.11.0
  printing: ^5.13.4
  path_provider: ^2.1.5
  share_plus: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/qr/
    - assets/logo/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/splash_logo.png

  android: true
  ios: true

  android_12:
    image: assets/logo/splash_logo.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/app_icon.png
  min_sdk_android: 21