// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmmrHZlyC2o-zDWMET8ojcgtl_JqgzWnk',
    appId: '1:1034614519401:web:5975a055c1ee912f4d14f8',
    messagingSenderId: '1034614519401',
    projectId: 'coaching-erp-c6f7e',
    authDomain: 'coaching-erp-c6f7e.firebaseapp.com',
    storageBucket: 'coaching-erp-c6f7e.firebasestorage.app',
    measurementId: 'G-QY9X6NQDM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuseGSiVuLX0f7oyOJNkapBvyijL23Bo',
    appId: '1:1034614519401:android:68e162ef2ad7963a4d14f8',
    messagingSenderId: '1034614519401',
    projectId: 'coaching-erp-c6f7e',
    storageBucket: 'coaching-erp-c6f7e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmu0q7wztiW1HtIwVmrXn5t9bHMlQ3ZuA',
    appId: '1:1034614519401:ios:1d8eb220fa18e55d4d14f8',
    messagingSenderId: '1034614519401',
    projectId: 'coaching-erp-c6f7e',
    storageBucket: 'coaching-erp-c6f7e.firebasestorage.app',
    iosBundleId: 'com.example.coachingErp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmu0q7wztiW1HtIwVmrXn5t9bHMlQ3ZuA',
    appId: '1:1034614519401:ios:1d8eb220fa18e55d4d14f8',
    messagingSenderId: '1034614519401',
    projectId: 'coaching-erp-c6f7e',
    storageBucket: 'coaching-erp-c6f7e.firebasestorage.app',
    iosBundleId: 'com.example.coachingErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmmrHZlyC2o-zDWMET8ojcgtl_JqgzWnk',
    appId: '1:1034614519401:web:f1a5f4e39c19ab994d14f8',
    messagingSenderId: '1034614519401',
    projectId: 'coaching-erp-c6f7e',
    authDomain: 'coaching-erp-c6f7e.firebaseapp.com',
    storageBucket: 'coaching-erp-c6f7e.firebasestorage.app',
    measurementId: 'G-KF776PQ6WQ',
  );
}





